# Alter these as needed

program    = "cam_back_front"
srcDir     = "src"
pathToRoot = "../.."

# Standard script below

import sys
sys.path.append(pathToRoot)
from BuildSupport import *

env = Environment()
makeSimpleProgram(env, pathToRoot, program, srcDir)
