# Alter these as needed

program    = "cam_back_front"
srcDir     = "src"
pathToRoot = "../.."

# Standard script below

import sys
sys.path.append(pathToRoot)
import BuildSupport
from SCons import Script

env = Script.Environment()
BuildSupport.makeSimpleProgram(env, pathToRoot, program, srcDir)
