# Alter these as needed

program    = "attr_visitor"
srcDir     = "src"
pathToRoot = "../.."

# Standard script below
from SCons import Script

import sys
sys.path.append(pathToRoot)
import BuildSupport

env = Script.Environment()
BuildSupport.makeSimpleProgram(env, pathToRoot, program, srcDir)
