# Alter these as needed

program    = "field3d_stats"
srcDir     = "src"
pathToRoot = "../.."

# Standard script below

import sys
sys.path.append(pathToRoot)
import BuildSupport
from SCons import Script

env = BuildSupport.Environment()
Script.makeSimpleProgram(env, pathToRoot, program, srcDir)
